### ISSUE TITLE
Error reading Safari cookies on Big Sur

### ISSUE THREAD

**Issue by ericmigi** [browserutils/kooky#41]
Attempting to run the example safari script https://github.com/zellyn/kooky#safari on Big Sur.

Getting this error:
```
2020/11/19 11:46:05 open /Users/eric/Library/Cookies/Cookies.binarycookies: operation not permitted
```

Even as sudo doesn't work, also tried granting the binary full disk access in settings, no luck. 

Has anyone been able to get this to work? Chrome works fine on Big Sur

**Comment by snipem** [comment]
Have you tried restarting the executing app after giving full disk access to them? I had to give full disk access to my terminal application.

**Comment by srlehn** [comment]
Cookie store location got updated in 9642b15 .
Tested on macos 13 (Ventura) (cgo+purego).
