### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by cflist** [browserutils/kooky#46]
When testing I could not find my cookie from Firefox. It might be due to the Multi-account container plugin. However I was testing without a container tab. It did work on Chrome for me.

Running Firefox version 92.0 (64-bits)

Maybe this has to do with the anti tracking features of Firefox.

**Comment by zellyn** [comment]
What OS is this? I have a Mac OS computer, and some Raspberry Pis running Linux, but don't have any Windows machines to test.

**Comment by cflist** [comment]
Windows 10 Pro 21H1, Build 19043.1237

**Comment by srlehn** [comment]
Support for the Firefox-Addon "Firefox Multi-Account Containers" has been added in #52. In case there are still issues with it please open a new issue.
