### ISSUE TITLE
Safari cookie file path is different in Ventura (MacOS 13).

### ISSUE THREAD

**Issue by acehinnnqru** [browserutils/kooky#57]
When I was trying to read cookies from Safari, I got stuck. After searching, I found that the cookie file is different which is in `~/Library/Containers/com.apple.Safari/Data/Library/Cookies`.

I have fixed this bug and I will create a PR with this issue.

**Comment by acehinnnqru** [comment]
> Any reason why this is not merged? Is this project dead?

This was been approved for a lone time. I think the maintainer might forget it...

@zellyn Could you help to check this issue and the related PR?

**Comment by srlehn** [comment]
should be fixed now
