### ISSUE TITLE
Thank you, very helpful project!

### ISSUE THREAD

**Issue by j178** [browserutils/kooky#61]
Hi, @zellyn and @srlehn 

I just wanted to take a moment to express my gratitude for this project. Although it is no longer actively maintained, I wanted to let you know that it is still working well and has been a great help to me. I appreciate the time and effort you guys put into creating and maintaining it, and your contributions to the open source community are truly appreciated. Thank you.

**Comment by srlehn** [comment]
Thanks!
I do plan to implement fixes, etc. every now and then. But this project has a very low priority for me.

Closing this as it is not an issue.
