### ISSUE TITLE
Unable to read cookies from chrome for windows from 18/9/2023 

### ISSUE THREAD

**Issue by phanik195** [browserutils/kooky#66]
cookies := kooky.ReadCookies(kooky.Valid, kooky.Name("ABC"))

	fmt.Println("cookies", &cookies)
	for _, cookie := range cookies {
		token_value = cookie.Value
		fmt.Println("Name " + cookie.Name + " :value " + cookie.Value)
	}
Note : the same is working for Mac.
Till last week able to cookie from chrome, but from 18/09/2023 we are facing an issue with windows.
Can anyone Please help us that would be great.

**Comment by zellyn** [comment]
Just curious: any chance you know how to set up a Windows-flavored test environment on a Mac or Raspberry Pi? I don't have any Windows machines to test with 😞

**Comment by phanik195** [comment]
No , @zellyn

**Comment by phanik195** [comment]
can anyone please help me on these its breaking your existing flow.

**Comment by phanik195** [comment]
[@zippoxer](http://github.com/zippoxer) , can you please help on these issue.

**Comment by srlehn** [comment]
I will try to test this soonish...

**Comment by srlehn** [comment]
Chrome 117.0.5938.150 on Windows 10 works fine.

- Are you _-importing "github.com/browserutils/kooky/browser/{all,chrome}"?
- is the cookie reading program running under the same user as the browser who set those?
- Is the Profile in a non-standard location?
- which Chrome and Windows version are you using=

**Comment by s34rch1ng-l0g1c** [comment]
Chrome 118.0.5993.88 on Windows does not work at all. 
Don't know what kind of changes maybe google did, but something happened.

**Comment by s34rch1ng-l0g1c** [comment]
Ok, since version 118 chrome cypher the cookies with a private key, based on account user password... so, to decrypt the cookies now it's needed the user password before. Since version 36 it was optional, now is mandatory. Game over with chrome... same happens in Android

**Comment by srlehn** [comment]
Retested with v118.0.5993.89 on Windows 10, it still works. I am unable to reproduce this.

The Chrome encryption is that way (DPAPI) for quite a while now, afaik there aren't any new changes to it, kooky knows how to decrypt those cookies (internal/chrome/chrome{,_windows}.go (getKeyringPassword())).

@s34rch1ng-l0g1c are you using the most current kooky commit? (go get -u github.com/browserutils/kooky@master)
Was Chrome closed when you tried reading cookies? What was the exact error message?

**Comment by s34rch1ng-l0g1c** [comment]
Thank you for your response, my fault. The problem was not being updated and chrome opened up.
