### ISSUE TITLE
Publish an unstable module branch

### ISSUE THREAD

**Issue by jeremy-cxf** [browserutils/kooky#67]
Looks like there was a lot of new functionality added that allows me refactor some existing code (cookie jars) for some of my projects. I would assume these changes are experimental, so best left for a branch stated as such.

However, go mod will still only resolve to pkg.dev@v0.2.0 where in certain functionality isn't available, this means I either have to look at vendoring, which even then is still iffy, and annoying to implement.

Would be good to actually just republish the module to the new namespace properly too, rather than rely on any redirecting, might be confusing for new comers of the package, where they will get errors like:

```
go: finding module for package github.com/browserutils/kooky/firefox
go: finding module for package github.com/browserutils/kooky
go: found github.com/browserutils/kooky in github.com/browserutils/kooky v0.2.0
go: found github.com/browserutils/kooky/firefox in github.com/browserutils/kooky v0.2.0
go: github.com/myproject/myproject/pkg/cookiepilf imports
        github.com/browserutils/kooky: github.com/browserutils/kooky@v0.2.0: parsing go.mod:
        module declares its path as: github.com/zellyn/kooky
                but was required as: github.com/browserutils/kooky
```

Thanks!

**Comment by srlehn** [comment]
published v0.2.1 - it should work again.
example code should be fine.
