### ISSUE TITLE
Chrome cookies not decrypted correctly on MacOS (chrome version 130.x)

### ISSUE THREAD

**Issue by DP19** [browserutils/kooky#89]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/browserutils/kooky/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

My chrome got updated yesterday and the tool i use that imports this library started to not work. I tracked it down to the decryption in https://github.com/browserutils/kooky/blob/b25315e83a1309a35bc0b2238e2d3978be6c3e75/internal/chrome/chrome.go#L320

It looks like there is a new padding at the begining of the decrypted values now, changing this to `return decrypted[32 : len(decrypted)-paddingLen], nil` returns the value correctly

### How to reproduce

1. update chrome to 130.x
2. run the `chrome_example_test.go` and see lots of ouput similar to `net/http: invalid byte '\u0099' in Cookie.Value; dropping invalid bytes`
3. see the output of the values have extra values at the font of them compared to inspecting them within chrome dev tools

for the example below, just visit google.com and inspect the AEC cookie and see the value difference between the output of the code and chrome dev tools

### Example code

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/browserutils/kooky"
	"github.com/browserutils/kooky/browser/chrome"
)

// on macOS:
var cookieStorePath = "/Google/Chrome/Default/Cookies"

func main() {
	// construct file path for the sqlite database containing the cookies
	dir, _ := os.UserConfigDir() // on macOS: "/<USER>/Library/Application Support/"
	cookieStoreFile := dir + cookieStorePath

	// read the cookies from the file
	// decryption is handled automatically
	cookies := chrome.TraverseCookies(cookieStoreFile).OnlyCookies()
	cookies = kooky.FilterCookies(context.TODO(), cookies, kooky.Domain(".google.com"), kooky.Name("AEC"))
	for cookie, _ := range cookies {
		fmt.Println(cookie)
	}
}

```

### Kooky version

v0.2.2

### Go compiler version

1.23.2

### Browser

Chrome 130.0.6723.59 (Official Build) (arm64)

### Operating system and version

MacOs Sanoma

**Comment by srlehn** [comment]
Hi, thank you for the bug report and the fix!
I can reproduced this on Linux with Chromium v132 with v10 cookies.
Do you know why (and perhaps when) this 32 byte long padding was added?

**Comment by DP19** [comment]
@srlehn im really not too sure to be honest. I just went as far to debug it and found the decrypted color value looked _almost_ right and then narrowed it down to a 32 bit padding. I can look around the chromium docs a little later

**Comment by srlehn** [comment]
I roughly looked through [components/os_crypt](https://github.com/chromium/chromium/tree/main/components/os_crypt/sync) and [crypto](https://github.com/chromium/chromium/tree/main/crypto) in the Chromium source code but wasn't yet able to find something. Testing on other platforms/chromium versions/key managers will have to wait a bit till I have time for it.

**Comment by Eitol** [comment]
Starting from version 24, the sha256 of the domain is prepended to the encrypted value  of the cookie.
Check: https://github.com/borisbabic/browser_cookie3/pull/215

So what you need to do is remove these first 32 bytes

**Comment by vmikhieienko** [comment]
@srlehn Hey, following up on this one, could you please review the PR done by @DP19?

**Comment by DP19** [comment]
We might have to come up with a patch strategy here. Master is currently a work in progress it seems for using the new go range capabilities in 1.22 and is broken in a few ways. I've got my own branch that is based in the latest release v0.2.2 and anyone who needs the fix I have a pr up for is welcome to use it

go.mod
```
replace github.com/browserutils/kooky v0.2.2 => github.com/DP19/kooky v0.2.4

```

v0.2.3 was a hack "just trim off the 32 bit padding always" to unblock me while I did the real fix
